application: kiri-bween
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /(.+\.php)$
  script: \1
  secure: always
  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always

- url: /
  static_files: htdocs/index.htm
  upload: /
  secure: always

- url: /images/(.*)
  static_files: images/\1
  upload: images/(.*)
  secure: always

- url: .*
  script: main.php
  secure: always
